/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as publicScanRouteImport } from './routes/(public)/scan'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports/index'
import { Route as AuthenticatedReportedIncidentsIndexRouteImport } from './routes/_authenticated/reported-incidents/index'
import { Route as AuthenticatedPatientConsultationReferralFormIndexRouteImport } from './routes/_authenticated/patient-consultation-referral-form/index'
import { Route as AuthenticatedOtherInformationIndexRouteImport } from './routes/_authenticated/other-information/index'
import { Route as AuthenticatedOtherDelegationIndexRouteImport } from './routes/_authenticated/other-delegation/index'
import { Route as AuthenticatedHighlightsIndexRouteImport } from './routes/_authenticated/highlights/index'
import { Route as AuthenticatedCurrentSituationIndexRouteImport } from './routes/_authenticated/current-situation/index'
import { Route as AuthenticatedBilletingQuartersIndexRouteImport } from './routes/_authenticated/billeting-quarters/index'
import { Route as AuthenticatedReportsDateRouteImport } from './routes/_authenticated/reports/$date'
import { Route as AuthenticatedReportsIdViewRouteImport } from './routes/_authenticated/reports/$id/view'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const publicScanRoute = publicScanRouteImport.update({
  id: '/(public)/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportedIncidentsIndexRoute =
  AuthenticatedReportedIncidentsIndexRouteImport.update({
    id: '/reported-incidents/',
    path: '/reported-incidents/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPatientConsultationReferralFormIndexRoute =
  AuthenticatedPatientConsultationReferralFormIndexRouteImport.update({
    id: '/patient-consultation-referral-form/',
    path: '/patient-consultation-referral-form/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOtherInformationIndexRoute =
  AuthenticatedOtherInformationIndexRouteImport.update({
    id: '/other-information/',
    path: '/other-information/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOtherDelegationIndexRoute =
  AuthenticatedOtherDelegationIndexRouteImport.update({
    id: '/other-delegation/',
    path: '/other-delegation/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHighlightsIndexRoute =
  AuthenticatedHighlightsIndexRouteImport.update({
    id: '/highlights/',
    path: '/highlights/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCurrentSituationIndexRoute =
  AuthenticatedCurrentSituationIndexRouteImport.update({
    id: '/current-situation/',
    path: '/current-situation/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBilletingQuartersIndexRoute =
  AuthenticatedBilletingQuartersIndexRouteImport.update({
    id: '/billeting-quarters/',
    path: '/billeting-quarters/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsDateRoute =
  AuthenticatedReportsDateRouteImport.update({
    id: '/reports/$date',
    path: '/reports/$date',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsIdViewRoute =
  AuthenticatedReportsIdViewRouteImport.update({
    id: '/reports/$id/view',
    path: '/reports/$id/view',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof authLoginRoute
  '/scan': typeof publicScanRoute
  '/reports/$date': typeof AuthenticatedReportsDateRoute
  '/billeting-quarters/': typeof AuthenticatedBilletingQuartersIndexRoute
  '/current-situation/': typeof AuthenticatedCurrentSituationIndexRoute
  '/highlights/': typeof AuthenticatedHighlightsIndexRoute
  '/other-delegation/': typeof AuthenticatedOtherDelegationIndexRoute
  '/other-information/': typeof AuthenticatedOtherInformationIndexRoute
  '/patient-consultation-referral-form/': typeof AuthenticatedPatientConsultationReferralFormIndexRoute
  '/reported-incidents/': typeof AuthenticatedReportedIncidentsIndexRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/reports/$id/view': typeof AuthenticatedReportsIdViewRoute
}
export interface FileRoutesByTo {
  '/login': typeof authLoginRoute
  '/scan': typeof publicScanRoute
  '/': typeof AuthenticatedIndexRoute
  '/reports/$date': typeof AuthenticatedReportsDateRoute
  '/billeting-quarters': typeof AuthenticatedBilletingQuartersIndexRoute
  '/current-situation': typeof AuthenticatedCurrentSituationIndexRoute
  '/highlights': typeof AuthenticatedHighlightsIndexRoute
  '/other-delegation': typeof AuthenticatedOtherDelegationIndexRoute
  '/other-information': typeof AuthenticatedOtherInformationIndexRoute
  '/patient-consultation-referral-form': typeof AuthenticatedPatientConsultationReferralFormIndexRoute
  '/reported-incidents': typeof AuthenticatedReportedIncidentsIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/reports/$id/view': typeof AuthenticatedReportsIdViewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(public)/scan': typeof publicScanRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/reports/$date': typeof AuthenticatedReportsDateRoute
  '/_authenticated/billeting-quarters/': typeof AuthenticatedBilletingQuartersIndexRoute
  '/_authenticated/current-situation/': typeof AuthenticatedCurrentSituationIndexRoute
  '/_authenticated/highlights/': typeof AuthenticatedHighlightsIndexRoute
  '/_authenticated/other-delegation/': typeof AuthenticatedOtherDelegationIndexRoute
  '/_authenticated/other-information/': typeof AuthenticatedOtherInformationIndexRoute
  '/_authenticated/patient-consultation-referral-form/': typeof AuthenticatedPatientConsultationReferralFormIndexRoute
  '/_authenticated/reported-incidents/': typeof AuthenticatedReportedIncidentsIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/reports/$id/view': typeof AuthenticatedReportsIdViewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/scan'
    | '/reports/$date'
    | '/billeting-quarters/'
    | '/current-situation/'
    | '/highlights/'
    | '/other-delegation/'
    | '/other-information/'
    | '/patient-consultation-referral-form/'
    | '/reported-incidents/'
    | '/reports/'
    | '/reports/$id/view'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/scan'
    | '/'
    | '/reports/$date'
    | '/billeting-quarters'
    | '/current-situation'
    | '/highlights'
    | '/other-delegation'
    | '/other-information'
    | '/patient-consultation-referral-form'
    | '/reported-incidents'
    | '/reports'
    | '/reports/$id/view'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(auth)/login'
    | '/(public)/scan'
    | '/_authenticated/'
    | '/_authenticated/reports/$date'
    | '/_authenticated/billeting-quarters/'
    | '/_authenticated/current-situation/'
    | '/_authenticated/highlights/'
    | '/_authenticated/other-delegation/'
    | '/_authenticated/other-information/'
    | '/_authenticated/patient-consultation-referral-form/'
    | '/_authenticated/reported-incidents/'
    | '/_authenticated/reports/'
    | '/_authenticated/reports/$id/view'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  publicScanRoute: typeof publicScanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(public)/scan': {
      id: '/(public)/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof publicScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reported-incidents/': {
      id: '/_authenticated/reported-incidents/'
      path: '/reported-incidents'
      fullPath: '/reported-incidents/'
      preLoaderRoute: typeof AuthenticatedReportedIncidentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patient-consultation-referral-form/': {
      id: '/_authenticated/patient-consultation-referral-form/'
      path: '/patient-consultation-referral-form'
      fullPath: '/patient-consultation-referral-form/'
      preLoaderRoute: typeof AuthenticatedPatientConsultationReferralFormIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/other-information/': {
      id: '/_authenticated/other-information/'
      path: '/other-information'
      fullPath: '/other-information/'
      preLoaderRoute: typeof AuthenticatedOtherInformationIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/other-delegation/': {
      id: '/_authenticated/other-delegation/'
      path: '/other-delegation'
      fullPath: '/other-delegation/'
      preLoaderRoute: typeof AuthenticatedOtherDelegationIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/highlights/': {
      id: '/_authenticated/highlights/'
      path: '/highlights'
      fullPath: '/highlights/'
      preLoaderRoute: typeof AuthenticatedHighlightsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/current-situation/': {
      id: '/_authenticated/current-situation/'
      path: '/current-situation'
      fullPath: '/current-situation/'
      preLoaderRoute: typeof AuthenticatedCurrentSituationIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billeting-quarters/': {
      id: '/_authenticated/billeting-quarters/'
      path: '/billeting-quarters'
      fullPath: '/billeting-quarters/'
      preLoaderRoute: typeof AuthenticatedBilletingQuartersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/$date': {
      id: '/_authenticated/reports/$date'
      path: '/reports/$date'
      fullPath: '/reports/$date'
      preLoaderRoute: typeof AuthenticatedReportsDateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/$id/view': {
      id: '/_authenticated/reports/$id/view'
      path: '/reports/$id/view'
      fullPath: '/reports/$id/view'
      preLoaderRoute: typeof AuthenticatedReportsIdViewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedReportsDateRoute: typeof AuthenticatedReportsDateRoute
  AuthenticatedBilletingQuartersIndexRoute: typeof AuthenticatedBilletingQuartersIndexRoute
  AuthenticatedCurrentSituationIndexRoute: typeof AuthenticatedCurrentSituationIndexRoute
  AuthenticatedHighlightsIndexRoute: typeof AuthenticatedHighlightsIndexRoute
  AuthenticatedOtherDelegationIndexRoute: typeof AuthenticatedOtherDelegationIndexRoute
  AuthenticatedOtherInformationIndexRoute: typeof AuthenticatedOtherInformationIndexRoute
  AuthenticatedPatientConsultationReferralFormIndexRoute: typeof AuthenticatedPatientConsultationReferralFormIndexRoute
  AuthenticatedReportedIncidentsIndexRoute: typeof AuthenticatedReportedIncidentsIndexRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
  AuthenticatedReportsIdViewRoute: typeof AuthenticatedReportsIdViewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedReportsDateRoute: AuthenticatedReportsDateRoute,
  AuthenticatedBilletingQuartersIndexRoute:
    AuthenticatedBilletingQuartersIndexRoute,
  AuthenticatedCurrentSituationIndexRoute:
    AuthenticatedCurrentSituationIndexRoute,
  AuthenticatedHighlightsIndexRoute: AuthenticatedHighlightsIndexRoute,
  AuthenticatedOtherDelegationIndexRoute:
    AuthenticatedOtherDelegationIndexRoute,
  AuthenticatedOtherInformationIndexRoute:
    AuthenticatedOtherInformationIndexRoute,
  AuthenticatedPatientConsultationReferralFormIndexRoute:
    AuthenticatedPatientConsultationReferralFormIndexRoute,
  AuthenticatedReportedIncidentsIndexRoute:
    AuthenticatedReportedIncidentsIndexRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
  AuthenticatedReportsIdViewRoute: AuthenticatedReportsIdViewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authLoginRoute: authLoginRoute,
  publicScanRoute: publicScanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
