export const PLAYING_VENUE_OPTIONS = [
  {
    municipality: "BAYUGAN CITY",
    venues: [
      "ACE SPORTS CENTRE",
      "AGUSAN DEL SUR COLLEGE",
      "AGUSAN DEL SUR PILOT LABORATORY SCHOOL",
      "BAYUGAN CENTRAL ELEM. SCHOOL SPED CENTER",
      "BAYUGAN CITY CONVENTION CENTER",
      "BAYUGAN CITY DOME",
      "BAYUGAN NCHS",
      "BAYUGAN WEST CES",
      "EAST BAYUGAN CES",
      "FILI NATIONAL HIGH SCHOOL",
      "LOPE A. ASIS MEMORIAL GYMNASIUM",
      "NOLI CES",
      "NOLI NATIONAL HIGH SCHOOL",
      "SALVACION CENTRAL ELEMENTARY SCHOOL",
      "SALVACION EVACUATION CENTER",
      "SALVACION NATIONAL HIGH SCHOOL",
      "SAN LORENZO RUIZ FUNCTION HALL",
    ],
  },

  {
    municipality: "BUNAWAN",
    venues: [
      "ASSCAT SOCIO-CULTURAL GYM",
      "BUNAWAN NATIONAL HIGH SCHOOL",
      "ZOTICO MODAY CULTURAL CENTER AND SPORTS COMPLEX(MUNICPAL GYMNASIUM)",
    ],
  },

  {
    municipality: "ESPERANZA",
    venues: [
      "ESPERANZA COVERED COURT",
    ],
  },

  {
    municipality: "PROSPERIDAD",
    venues: [
      "AGUSAN DEL SUR NATIONAL SCIENCE HIGH SCHOOL COVERED COURT",
      "ASSAT COMPOUND",
      "BACK OF THE PROVINCIAL SATELLITE AUDITING OFFICE (PSAO)",
      "DATU LIPUS MAKAPANDONG GOVERNOR D.O. PLAZA SPORTS COMPLEX",
      "DPWH COVERED COURT",
      "EAST PROSPERIDAD CENTRAL ELEMENTARY SCHOOL",
      "EOC EVACUATION CENTER",
      "NALIYAGAN OPEN FIELD NEAR DLMCC",
      "OPEN FIELD NEAR PPIO",
      "PROSPERIDAD NHS",
      "PROVINCIAL ENGINEERING COMPOUND",
      "PROVINCIAL EVACUATION CENTER",
      "SALVACION ES",
      "STA IRENE CENTRAL ES",
      "STA. IRENE NATIONAL HIGH SCHOOL",
    ],
  },

  {
    municipality: "ROSARIO",
    venues: [
      "BAYUGAN III NATIONAL HIGH SCHOOL",
      "BONIFACIO CENTRAL ELEMENTARY SCHOOL",
      "DATU LIPUS MAKAPANDONG NATIONAL HIGH SCHOOL",
      "EUTIQUIO O. BADE SR. SPORTS AND CULTURAL CENTER",
      "ROSARIO CES",
    ],
  },

  {
    municipality: "SAN FRANCISCO",
    venues: [
      "AGUSAN DEL SUR NATIONAL HIGH SCHOOL",
      "ALEGRIA COVERED COURT",
      "ASELCO FUNCTION HALL",
      "BITAN-AGAN COVERED COURT",
      "LAPINIGAN CES",
      "LAPINIGAN NATIONAL HIGH SCHOOL",
      "PERA-MPC OPEN FIELD",
      "SAN FRANCISCO GYMNASIUM",
      "SAN FRANCISCO PILOT CES",
    ],
  },

  {
    municipality: "TALACOGON",
    venues: [
      "DEL MONTE CENTRAL ELEMENTARY SCHOOL",
      "DEL MONTE EVACUATION CENTER",
      "DEL MONTE NATIONAL HIGH SCHOOL",
      "LABNIG OPEN SPACE",
      "TALACOGON MUNICIPAL GYM",
    ],
  },
] as const