export const ARS_PERMISSIONS = {
  BILLETING_QUARTERS: 13,
  HIGHLIGHTS: 12,
  PLAYING_VENUES: 14,
  CURRENT_SITUATIONS: 15,
  REPORTED_INCIDENTS: 16,
  OTHER_INFORMATION: 17,
  WEATHER_UPDATES: 18,
  ID_PRINTING: 19,
} as const